services:
  cosmosapi:
    image: ${DOCKER_REGISTRY-}cosmosapi
    build:
      context: .
      dockerfile: CosmosAPI/Dockerfile

  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports: ["8081:8081", "1234:1234"]
    command: ["--protocol", "https-insecure"]
    # command: ["--protocol", "https"]
    environment:
      - GATEWAY_PUBLIC_ENDPOINT=cosmos-db
      
networks:
  platform-network:
    name: platform-network
    driver: bridge
